In [1]:
import pandas as pd
import re

In [2]:
ca_demo = pd.read_csv("/Users/susanlieu/Documents/LIS590OMO/Data/CA_DEMO/CA_demographics.csv")

ca_demo.head()

,FIPS,Geographic Identifier,Name of Area,Qualifying Name,State/U.S.-Abbreviation (USPS),Summary Level,Geographic Component,File Identification,Logical Record Number,US,...,"% Civilian Population 16 to 19 Years: High School Graduate, or Enrolled (in School)",Median Household Income (In 2017 Inflation Adjusted Dollars),Population Under 18 Years of Age for Whom Poverty Status Is Determined:,Population Under 18 Years of Age for Whom Poverty Status Is Determined: Living in Poverty,Population Under 18 Years of Age for Whom Poverty Status Is Determined: At or Above Poverty Level,% Population Under 18 Years of Age for Whom Poverty Status Is Determined: Living in Poverty,% Population Under 18 Years of Age for Whom Poverty Status Is Determined: At or Above Poverty Level,Households,Households with Housing Costs more than 30% of Income,% Households with Housing Costs more than 30% of Income
0,Geo_FIPS,Geo_GEOID,Geo_NAME,Geo_QName,Geo_STUSAB,Geo_SUMLEV,Geo_GEOCOMP,Geo_FILEID,Geo_LOGRECNO,Geo_US,...,PCT_SE_T030_003,SE_T057_001,SE_T114_001,SE_T114_002,SE_T114_003,PCT_SE_T114_002,PCT_SE_T114_003,SE_T255_001,SE_T255_002,PCT_SE_T255_002
1,6001,05000US06001,"Alameda County, California","Alameda County, California",ca,50,0,ACSSF,13,NaN,...,97.33,85743,340749,44382,296367,13.02,86.98,569070,208963,36.72
2,6003,05000US06003,"Alpine County, California","Alpine County, California",ca,50,0,ACSSF,14,NaN,...,100,63438,243,42,201,17.28,82.72,304,122,40.13
3,6005,05000US06005,"Amador County, California","Amador County, California",ca,50,0,ACSSF,15,NaN,...,96.14,60636,5564,1127,4437,20.26,79.74,14185,4024,28.37
4,6007,05000US06007,"Butte County, California","Butte County, California",ca,50,0,ACSSF,16,NaN,...,98,46516,44392,9542,34850,21.49,78.51,86167,31259,36.28

In [3]:
ca_demo.shape

(59, 133)

In [4]:
ca_demo = ca_demo.drop([0])

In [5]:
#0,1,3:55
    
ca_demo = ca_demo.drop(columns=["FIPS", "Geographic Identifier", "Qualifying Name", "State/U.S.-Abbreviation (USPS)",
                      "Summary Level", "Geographic Component", "File Identification", "Logical Record Number",
                      "US", "Region", "Division", "State (Census Code)", "State (FIPS)", "County", "County Subdivision (FIPS)",
                      "Place (FIPS Code)", "Place (State FIPS + Place FIPS)", "Census Tract","Block Group", "Consolidated City",
                      "American Indian Area/Alaska Native Area/Hawaiian Home Land (Census)", "American Indian Area/Alaska Native Area/Hawaiian Home Land (FIPS)",
                      "American Indian Trust Land/Hawaiian Home Land Indicator", "American Indian Tribal Subdivision (Census)",
                      "American Indian Tribal Subdivision (FIPS)", "Alaska Native Regional Corporation (FIPS)", "Metropolitan and Micropolitan Statistical Area",
                      "Combined Statistical Area", "Metropolitan Division", "Metropolitan Area Central City", "Metropolitan/Micropolitan Indicator Flag",
                      "New England City and Town Combined Statistical Area", "New England City and Town Area", "New England City and Town Area Division",
                      "Urban Area", "Urban Area Central Place", "Current Congressional District ***", "State Legislative District Upper",
                      "State Legislative District Lower", "Voting District", "ZIP Code Tabulation Area (3-digit)", "ZIP Code Tabulation Area (5-digit)",
                      "Subbarrio (FIPS)", "School District (Elementary)", "School District (Secondary)", "School District (Unified)", 
                      "Urban/Rural", "Principal City Indicator", "Principal City Indicator", "Traffic Analysis Zone", "Urban Growth Area",
                      "Tribal Tract", "Tribal Block Group", "Public Use Microdata Area - 5% File", "Public Use Microdata Area - 1% File", "Total Population:",
                      "Total Population: Two or More Races", "Population Under 18 Years of Age for Whom Poverty Status Is Determined:", 
                      "Population Under 18 Years of Age for Whom Poverty Status Is Determined: Living in Poverty",
                      "Population Under 18 Years of Age for Whom Poverty Status Is Determined: At or Above Poverty Level",
                      "% Population Under 18 Years of Age for Whom Poverty Status Is Determined: At or Above Poverty Level",
                      "Households", "Households with Housing Costs more than 30% of Income", "% Households with Housing Costs more than 30% of Income",
                      "Civilian Population 16 to 19 Years: Not High School Graduate, Not Enrolled (Dropped Out)",
                      "Civilian Population 16 to 19 Years: High School Graduate, or Enrolled (in School)",
                      "% Civilian Population 16 to 19 Years: Not High School Graduate, Not Enrolled (Dropped Out)",
                      "% Civilian Population 16 to 19 Years: High School Graduate, or Enrolled (in School)",
                      "% Total Population: Two or More Races", "Total Population.1", "Total Population: Not Hispanic or Latino",
                      "Total Population: Not Hispanic or Latino: White Alone", "Total Population: Not Hispanic or Latino: Black or African American Alone",
                      "Total Population: Not Hispanic or Latino: American Indian and Alaska Native Alone",
                      "Total Population: Not Hispanic or Latino: Asian Alone", "Total Population: Not Hispanic or Latino: Native Hawaiian and Other Pacific Islander Alone", 
                      "Total Population: Not Hispanic or Latino: Some Other Race Alone",
                      "Total Population: Not Hispanic or Latino: Two or More Races",
                      "Total Population: Hispanic or Latino: White Alone",
                      "Total Population: Hispanic or Latino: Black or African American Alone", 
                      "Total Population: Hispanic or Latino: American Indian and Alaska Native Alone",
                      "Total Population: Hispanic or Latino: Asian Alone",
                      "Total Population: Hispanic or Latino: Native Hawaiian and Other Pacific Islander Alone",
                      "Total Population: Hispanic or Latino: Some Other Race Alone",
                      "Total Population: Hispanic or Latino: Two or More Races",
                      "% Total Population: Not Hispanic or Latino",
                      "% Total Population: Not Hispanic or Latino: White Alone",
                      "% Total Population: Not Hispanic or Latino: Black or African American Alone",
                      "% Total Population: Not Hispanic or Latino: American Indian and Alaska Native Alone",
                      "% Total Population: Not Hispanic or Latino: Asian Alone",
                      "% Total Population: Not Hispanic or Latino: Native Hawaiian and Other Pacific Islander Alone",
                      "% Total Population: Not Hispanic or Latino: Some Other Race Alone",
                      "% Total Population: Not Hispanic or Latino: Two or More Races",
                      "% Total Population: Hispanic or Latino: White Alone",
                      "% Total Population: Hispanic or Latino: Black or African American Alone",
                      "% Total Population: Hispanic or Latino: American Indian and Alaska Native Alone",
                      "% Total Population: Hispanic or Latino: Asian Alone",
                      "% Total Population: Hispanic or Latino: Native Hawaiian and Other Pacific Islander Alone",
                      "% Total Population: Hispanic or Latino: Some Other Race Alone",
                      "% Total Population: Hispanic or Latino: Two or More Races",
                      "Population 25 Years and Over:",
                      "Population 25 Years and Over: Less than High School",
                      "Population 25 Years and Over: High School Graduate or More (Includes Equivalency)",
                      "Population 25 Years and Over: Some College or More",
                      "Population 25 Years and Over: Bachelor's Degree or More",
                      "Population 25 Years and Over: Master's Degree or More",
                      "Population 25 Years and Over: Professional School Degree or More",
                      "Population 25 Years and Over: Doctorate Degree"])

In [6]:
ca_demo.shape

(58, 26)

In [7]:
ca_demo.head()

,Name of Area,Total Population,Total Population: White Alone,Total Population: Black or African American Alone,Total Population: American Indian and Alaska Native Alone,Total Population: Asian Alone,Total Population: Native Hawaiian and Other Pacific Islander Alone,Total Population: Some Other Race Alone,% Total Population: White Alone,% Total Population: Black or African American Alone,...,% Population 25 Years and Over: Less than High School,% Population 25 Years and Over: High School Graduate or More (Includes Equivalency),% Population 25 Years and Over: Some College or More,% Population 25 Years and Over: Bachelor's Degree or More,% Population 25 Years and Over: Master's Degree or More,% Population 25 Years and Over: Professional School Degree or More,% Population 25 Years and Over: Doctorate Degree,Civilian Population 16 to 19 Years:,Median Household Income (In 2017 Inflation Adjusted Dollars),% Population Under 18 Years of Age for Whom Poverty Status Is Determined: Living in Poverty
1,"Alameda County, California",1629615,694720,180446,10152,471335,13652,155248,42.63,11.07,...,12.46,87.54,69.65,44.71,18.98,5.86,2.87,76292,85743,13.02
2,"Alpine County, California",1203,826,18,263,8,8,0,68.66,1.5,...,10.23,89.77,55.61,25.65,10.73,3.7,2.47,109,63438,17.28
3,"Amador County, California",37306,32453,796,295,582,84,1366,86.99,2.13,...,10.29,89.71,62.66,22.1,7.3,3.02,1,1633,60636,20.26
4,"Butte County, California",225207,185221,3372,2633,10174,424,9646,82.24,1.5,...,11.25,88.75,66.12,26.62,8.93,3.22,0.99,13094,46516,21.49
5,"Calaveras County, California",45057,41356,261,497,527,208,472,91.79,0.58,...,9.99,90.01,62.42,19.28,6.71,1.73,0.61,1922,54800,18.91

In [8]:
ca_demo = ca_demo.rename(columns={"Name of Area": "County"})

In [9]:
ca_demo["County"] = ca_demo["County"].apply(lambda x: re.sub(r"(\sCounty\,\sCalifornia)","",x))
ca_demo

,County,Total Population,Total Population: White Alone,Total Population: Black or African American Alone,Total Population: American Indian and Alaska Native Alone,Total Population: Asian Alone,Total Population: Native Hawaiian and Other Pacific Islander Alone,Total Population: Some Other Race Alone,% Total Population: White Alone,% Total Population: Black or African American Alone,...,% Population 25 Years and Over: Less than High School,% Population 25 Years and Over: High School Graduate or More (Includes Equivalency),% Population 25 Years and Over: Some College or More,% Population 25 Years and Over: Bachelor's Degree or More,% Population 25 Years and Over: Master's Degree or More,% Population 25 Years and Over: Professional School Degree or More,% Population 25 Years and Over: Doctorate Degree,Civilian Population 16 to 19 Years:,Median Household Income (In 2017 Inflation Adjusted Dollars),% Population Under 18 Years of Age for Whom Poverty Status Is Determined: Living in Poverty
1,Alameda,1629615,694720,180446,10152,471335,13652,155248,42.63,11.07,...,12.46,87.54,69.65,44.71,18.98,5.86,2.87,76292,85743,13.02
2,Alpine,1203,826,18,263,8,8,0,68.66,1.5,...,10.23,89.77,55.61,25.65,10.73,3.7,2.47,109,63438,17.28
3,Amador,37306,32453,796,295,582,84,1366,86.99,2.13,...,10.29,89.71,62.66,22.1,7.3,3.02,1,1633,60636,20.26
4,Butte,225207,185221,3372,2633,10174,424,9646,82.24,1.5,...,11.25,88.75,66.12,26.62,8.93,3.22,0.99,13094,46516,21.49
5,Calaveras,45057,41356,261,497,527,208,472,91.79,0.58,...,9.99,90.01,62.42,19.28,6.71,1.73,0.61,1922,54800,18.91
6,Colusa,21479,18964,198,247,328,16,1169,88.29,0.92,...,30.57,69.43,46.24,15.72,4.44,1.94,0.27,1262,56481,20.7
7,Contra Costa,1123678,658569,96345,5410,180072,5542,102876,58.61,8.57,...,10.91,89.09,71.2,40.74,14.86,4.83,1.91,57007,88456,12.43
8,Del Norte,27442,21073,493,2158,776,21,909,76.79,1.8,...,18.44,81.56,49.49,14.44,5.71,2.28,0.75,1133,41287,31.19
9,El Dorado,185015,161881,1789,1347,7864,333,5026,87.5,0.97,...,7.1,92.9,71.44,33.33,11.98,3.99,1.42,9246,74885,11.59
10,Fresno,971616,617322,47715,9784,97966,1947,158359,63.54,4.91,...,25.33,74.67,51.83,20.12,6.8,2.52,0.86,56709,48730,36.48
11,Glenn,27935,23191,220,541,729,113,2542,83.02,0.79,...,27.49,72.51,45.22,12.99,2.84,1.22,0.38,1644,46260,25.47
12,Humboldt,135490,109346,1609,7042,3926,418,5318,80.7,1.19,...,9.45,90.55,66.51,29.43,10.09,3.7,1.38,7645,43718,22.46
13,Imperial,179957,117188,4785,1979,2584,261,44841,65.12,2.66,...,31.59,68.41,44.88,14.28,4.43,0.86,0.17,10659,44779,30.97
14,Inyo,18195,14685,174,2093,272,34,409,80.71,0.96,...,11.35,88.65,58.31,25.28,9.38,2.46,1.25,814,51500,13.35
15,Kern,878744,660196,48078,9739,41263,1620,88403,75.13,5.47,...,26.19,73.81,46.13,15.79,5.24,1.57,0.62,52584,50826,31.33
16,Kings,150183,99117,9597,2259,5694,367,26842,66,6.39,...,27.08,72.92,47.38,13.05,3.78,1.38,0.27,8434,49742,28.74
17,Lake,64095,49841,1493,2201,953,33,7951,77.76,2.33,...,15.29,84.71,54.44,15.34,5.45,1.83,0.59,2960,40446,31.62
18,Lassen,31470,25615,2748,968,463,219,865,81.39,8.73,...,17.66,82.34,49.94,12.4,4.55,1.64,0.54,1179,54083,20.72
19,Los Angeles,10105722,5232835,828981,68211,1460508,27691,2101084,51.78,8.2,...,21.84,78.16,57.44,31.23,10.88,3.63,1.3,543922,61015,24.02
20,Madera,154440,118390,4938,2556,3303,224,20081,76.66,3.2,...,28.39,71.61,46.82,13.84,4.53,1.58,0.63,9449,48210,31.5
21,Marin,260814,203898,5759,689,14912,492,22779,78.18,2.21,...,6.75,93.25,82.02,57.51,25.05,9.67,3.08,10406,104703,9.67
22,Mariposa,17658,15715,215,467,168,56,309,89,1.22,...,9.89,90.11,61.91,24.42,9.65,2.82,0.97,632,51385,17.5
23,Mendocino,87497,72378,620,3703,1509,186,4644,82.72,0.71,...,13.1,86.9,60.67,24.78,8.38,3.13,1.22,4419,46528,24.43
24,Merced,267390,153649,8621,1826,20224,456,70466,57.46,3.22,...,31.11,68.89,43.79,13.76,4.81,1.58,0.72,18658,46338,33.36
25,Modoc,9017,8244,65,368,105,8,31,91.43,0.72,...,14.49,85.51,55.05,16.58,4.04,0.73,0,435,39296,20.42
26,Mono,14058,11987,74,374,280,0,940,85.27,0.53,...,15.27,84.73,65.8,31.54,8.33,1.99,0.3,491,60595,11.95
27,Monterey,433168,281181,11278,2890,24867,2038,93107,64.91,2.6,...,28.8,71.2,50.5,23.92,9.45,3.16,1.25,24661,63249,21.59
28,Napa,141005,102418,2998,1236,11150,297,17573,72.63,2.13,...,15.27,84.73,66.63,34.57,11.76,4.49,1.45,7485,79637,8.97
29,Nevada,98838,91016,582,930,1123,99,1823,92.09,0.59,...,6.45,93.55,75.04,35.83,12.98,4.13,1.25,4471,60610,15.1
30,Orange,3155816,1960484,53262,14468,621178,9620,373605,62.12,1.69,...,15.29,84.71,67.4,39.07,13.86,4.38,1.57,168512,81851,16.42
31,Placer,374985,310295,5756,2029,25999,874,11661,82.75,1.53,...,5.54,94.46,75.4,37.49,12.48,3.88,1.14,18701,80488,8.3
32,Plumas,18724,16781,160,398,148,55,368,89.62,0.85,...,6.43,93.57,68.11,22.59,10.12,2.42,0.55,757,50266,12.78
33,Riverside,2355002,1450473,148960,19865,148213,6863,474855,61.59,6.33,...,18.91,81.09,54.71,21.52,7.84,2.28,0.87,141857,60807,21.31
34,Sacramento,1495400,877495,147425,10384,229441,16019,109241,58.68,9.86,...,12.98,87.02,64.52,29.87,10.15,3.32,1.07,75776,60239,22.61
35,San Benito,58671,48136,442,426,1649,124,5181,82.04,0.75,...,20.9,79.1,54.44,19.19,5.86,1.91,0.7,3552,80760,14.45
36,San Bernardino,2121220,1312700,178674,17046,146650,6660,360213,61.88,8.42,...,20.8,79.2,52.98,19.77,6.94,1.9,0.74,129131,57156,25.82
37,San Diego,3283665,2325434,164571,21064,384154,14182,207640,70.82,5.01,...,13.3,86.7,68.1,37.36,14.36,4.82,2.08,173100,70588,17.06
38,San Francisco,864263,408266,45654,3306,295347,3226,64800,47.24,5.28,...,12.1,87.9,75.6,55.79,22.37,7.69,2.74,25022,96265,11.37
39,San Joaquin,724153,404806,50433,4304,109359,4233,80536,55.9,6.96,...,21.56,78.44,51.07,18.08,5.77,1.84,0.65,43844,57813,23.06
40,San Luis Obispo,280119,240584,5393,2041,10276,280,11804,85.89,1.93,...,9.53,90.47,70.66,34,12.85,4.54,2.05,19462,67175,12.9
41,San Mateo,763450,397718,18577,2611,210816,10797,82231,52.09,2.43,...,11.06,88.94,73.44,48.54,20.33,7.28,3.25,31819,105667,8.73
42,Santa Barbara,442996,330827,8307,3869,23927,732,55909,74.68,1.88,...,19.56,80.44,63.02,33.27,13.46,4.99,2.29,32040,68023,19.37
43,Santa Clara,1911226,869630,48314,9273,671511,7438,210878,45.5,2.53,...,12.45,87.55,72.77,50.02,23.18,6.34,3.63,91461,106761,9.73
44,Santa Cruz,273263,211116,2424,1507,12547,261,32786,77.26,0.89,...,13.59,86.41,70.88,39.75,16.12,5.64,2.74,19750,73663,16.95
45,Shasta,178919,155538,2007,4404,5310,153,3711,86.93,1.12,...,9.32,90.68,64.95,21.36,7.37,2.49,0.58,8973,47258,25.4
46,Sierra,2885,2797,4,28,0,0,1,96.95,0.14,...,7.09,92.91,67.49,21.4,6.53,1.6,0.73,108,44190,10.56
47,Siskiyou,43530,37064,675,1511,687,161,690,85.15,1.55,...,10.69,89.31,64.22,22.69,7.64,2.23,0.58,1971,40884,26.62
48,Solano,434981,229351,61752,2106,66432,3818,39516,52.73,14.2,...,12.41,87.59,64.3,25.57,7.71,2.39,0.83,21702,72950,16.59
49,Sonoma,500943,377401,7848,5750,19605,1677,62101,75.34,1.57,...,12.32,87.68,68.55,33.85,12.17,4.24,1.43,23987,71769,13.05
50,Stanislaus,535684,400661,15121,3789,29488,3670,59966,74.79,2.82,...,22.25,77.75,49.54,16.72,5.37,1.89,0.52,30746,54260,23.2
51,Sutter,95583,67211,1970,904,14565,539,4185,70.32,2.06,...,21.35,78.65,53.74,17.51,5.54,1.74,0.42,5147,54347,23.33
52,Tehama,63247,54371,379,1505,907,27,3505,85.97,0.6,...,15.96,84.04,51.64,14.37,4.62,1.49,0.28,2918,42512,30.91
53,Trinity,13037,11284,104,559,161,118,416,86.55,0.8,...,10.23,89.77,57.89,19.47,4.06,1.03,0.51,734,36563,24.5
54,Tulare,458809,361911,7177,5787,16081,629,52819,78.88,1.56,...,31.36,68.64,42.81,13.84,4.55,1.36,0.42,29320,44871,36.19
55,Tuolumne,53899,47181,975,931,609,155,1636,87.54,1.81,...,9.28,90.72,61.53,20.57,7.47,2.47,0.72,2342,54325,13.8
56,Ventura,847834,677010,14805,6929,60986,1658,49513,79.85,1.75,...,16.01,83.99,65.07,32.59,12.2,4,1.64,46337,81972,14.39
57,Yolo,212605,142841,5301,1333,29138,911,19837,67.19,2.49,...,13.88,86.12,67.26,40.57,19.84,9.24,5.22,17436,61621,16.32
58,Yuba,74644,54601,2484,1033,4823,300,5269,73.15,3.33,...,17.85,82.15,57.58,16.38,4.41,1.05,0.18,3656,51776,24.97

In [10]:
ca_demo.shape

(58, 26)

In [11]:
ca_demo.to_csv(r"/Users/susanlieu/Documents/LIS590OMO/Data/ca_demo.csv", sep=",", encoding="utf-8")